spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        format_sql: 'false'
        show_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: wjstjd741
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://13.209.48.48:3306/Schedule?guseUnicode=true&characterEncoding=UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      schema-locations: classpath:data.sql
      mode: never
jwt:
  secret: mySecretasdsadaskdvksnkansdkjnajsdnsakdaskjdnaskjdnaskdsadasdasdhsakjdhsajdhajajsdhjkdjkdakshskjdshajdskjsksahdkjaksdassjdashjdsahjhkjsdhaksksdadkjkahdakskjdshkjdshkjdsakjdhsa
logging:
  level:
    # 패키지 레벨 설정
    org.springframework: INFO
    # 클래스 레벨 설정
    com.example.project.Controller: DEBUG






